kind: Service
apiVersion: v1
metadata:
  name: hello-service
  namespace: gitops-prod
spec:
  selector:
    app: hello
  ports:
  - protocol: TCP
    port: 8000
    nodePort: 32321
  type: NodePort
